// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4rotipYGBiocISAJTEYsezX2YuKpm90A',
    appId: '1:756938865396:web:ca7e33544ea83e277b7ca1',
    messagingSenderId: '756938865396',
    projectId: 'nebat-ae947',
    authDomain: 'nebat-ae947.firebaseapp.com',
    storageBucket: 'nebat-ae947.appspot.com',
    measurementId: 'G-3PFD3NPH05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfED3voWWLQSVLfohyncmxatY9QyrHbAI',
    appId: '1:756938865396:android:dde61453c14adfa97b7ca1',
    messagingSenderId: '756938865396',
    projectId: 'nebat-ae947',
    storageBucket: 'nebat-ae947.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgjKimUsASKmkYYn8OhnytOmEIxl97Bdo',
    appId: '1:756938865396:ios:5c1316a5d99c12867b7ca1',
    messagingSenderId: '756938865396',
    projectId: 'nebat-ae947',
    storageBucket: 'nebat-ae947.appspot.com',
    iosClientId: '756938865396-jp00t4jep39usp24dagd17q3id200uih.apps.googleusercontent.com',
    iosBundleId: 'com.example.nebat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgjKimUsASKmkYYn8OhnytOmEIxl97Bdo',
    appId: '1:756938865396:ios:5c1316a5d99c12867b7ca1',
    messagingSenderId: '756938865396',
    projectId: 'nebat-ae947',
    storageBucket: 'nebat-ae947.appspot.com',
    iosClientId: '756938865396-jp00t4jep39usp24dagd17q3id200uih.apps.googleusercontent.com',
    iosBundleId: 'com.example.nebat',
  );
}
